name: Create Release Pull Request

on:
  workflow_dispatch:

jobs:
  create_release_pr:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: create_branch
        run: |
          git checkout -b release
          git push origin HEAD
          gh pr create -B main -H release --title 'Merge release into main' --body 'Created by Github action'
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
