name: Create a pull request for the release
on:
  push:
    branches:
      - release/**

jobs:
  create_release_pr:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: some_name
        run: |
          gh pr create -B main -H ${{ github.head_ref || github.ref_name }} --title 'Merge release into main' --body 'Created by Github action'
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
