name: Create a pull request for the release
on:
  push:
    branches:
      - release/*

jobs:
  create_release_pull_request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: main
