name: Create Release Pull Request

on:
  workflow_dispatch:
    inputs:
      version_level:
        type: choice
        name: Version Level
        description: The release version bump major.minor.patch
        options:
        - patch
        - minor
        - major

jobs:
  create_release_pr:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: create_branch
        run: |
          git config --global user.email 'github_robot@modolabs.com'
          git config --global user.name "GitHub Robot"
          git checkout -b automated_release
          git commit --allow-empty -m "The patch level is #$VERSION_LEVEL"
          git push origin HEAD
          gh pr create -B main -H automated_release --title 'Merge release into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_LEVEL: ${{ inputs.version_level }}
