name: Merge back into develop
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    jobs:
      merge-branch:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master

          - name: Merge main -> develop
            uses: devmasx/merge-branch@master
            with:
              type: now
              target_branch: develop
              github_token: ${{ secrets.GITHUB_TOKEN }}
