name: Merge back into develop
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  merge_into_develop:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Merge main into develop
          body: After a release we need to update develop from main.
          branch: develop
          base: main
